### ISSUE TITLE
Crash with Buildcraft during game loading

### ISSUE THREAD

**Issue by QuantumStatement** [PersonTheCat/ore_stone_variants#1]
Minecraft 1.12.2
Forge 14.23.2.2611
Ore Stone Variants 2.0
Buildcraft 7.99.15

[Crash Report](https://github.com/PersonTheCat/ore_stone_variants/files/1852342/crash-2018-03-27_17.17.21-client.txt)

**Comment by PersonTheCat** [comment]
Sorry for the copy and paste response, but here is the current situation, taken from another response on curseforge.com: 

"I have looked into this, and here's what I'm seeing: There are several lines in my code that use an item's meta value as an index to retrieve a language key. BuildCraft is trying to use Forge's OreDictionary's wildcard card value in place of a block's meta value in that location, causing an out of bounds exception. Long story short, I don't use that value anywhere in my mod, so I'm pretty sure the problem isn't on my end. I can stop it from crashing, but that would most likely just cause other issues instead (e.g. most variants not getting recognized by the game). I will try sometime soon to see what I can come up with, but I don't think I can make any promises because of the circumstances, unfortunately. :/"

Sorry about that! I'll try to put something out in the next day or two.

**Comment by PersonTheCat** [comment]
Hello. 

I have changed something just to get the mod to be able to run. Please try the latest build as soon as you get the chance and let me know if it's working for you. 

-Cat

**Comment by QuantumStatement** [comment]
Yes, latest build is working
