### ISSUE TITLE
crash games at boot time

### ISSUE THREAD

**Issue by KiraLinux** [PersonTheCat/ore_stone_variants#10]
1.12.2-forge1.12.2-14.23.3.2661
ore_stone_variants-2.6
[crash-reports.zip](https://github.com/PersonTheCat/ore_stone_variants/files/1916464/crash-reports.zip)

**Comment by PersonTheCat** [comment]
Hello. This bug was introduced in 2.6, which was subsequently removed from curseforge.com for this reason. Basically, the wrong library was automatically imported through my compiler and for some reason wasn't available outside of that workspace. Please try version 2.7 instead and let me know if you're still experiencing the same issue. 

Thanks! -Cat
