### ISSUE TITLE
[1.12] Many, many issues...

### ISSUE THREAD

**Issue by EnderBro123** [PersonTheCat/ore_stone_variants#106]
Not sure what are causing these, but this mod is pretty much unuseable.

[crash-2020-12-20_12.52.20-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721517/crash-2020-12-20_12.52.20-client.txt)
[crash-2020-12-20_12.56.49-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721518/crash-2020-12-20_12.56.49-client.txt)
[crash-2020-12-20_13.05.19-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721519/crash-2020-12-20_13.05.19-client.txt)
[crash-2020-12-20_13.13.46-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721520/crash-2020-12-20_13.13.46-client.txt)

**Comment by PersonTheCat** [comment]
These crashes are very much intentional. Make sure to read the crash report. "There is no block named x" means you're trying to generate variants from x, but you have x disabled.

**Comment by EnderBro123** [comment]
How do I remove them then without the game crashing.

**Comment by EnderBro123** [comment]
@PersonTheCat

**Comment by Arkytek** [comment]
> Not sure what are causing these, but this mod is pretty much unuseable.
> 
> [crash-2020-12-20_12.52.20-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721517/crash-2020-12-20_12.52.20-client.txt)
> [crash-2020-12-20_12.56.49-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721518/crash-2020-12-20_12.56.49-client.txt)
> [crash-2020-12-20_13.05.19-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721519/crash-2020-12-20_13.05.19-client.txt)
> [crash-2020-12-20_13.13.46-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5721520/crash-2020-12-20_13.13.46-client.txt)

complains about mod being unusable when you literally edited the files to break it yourself... what an idiot lmao

**Comment by PersonTheCat** [comment]
I just want to clarify that these issues were resolved on Discord. For anyone wondering, the problem is that you need to define which ores you want to spawn and where. There are default settings that work for some people, but if you want a different set of ores, then some effort will be required. That's just how this works. 

This mod does have issues, but it is not completely broken. I expect that most of my users are mod pack developers who are willing to read the crash logs. This is how I communicate what changes they need to make. You just have to read carefully. If you're interested in helping me improve this, we do need a Wiki and I could use some help. Send me a dm. 

I also wanna clarify that this is not the place to insult me and demand that I make changes on Christmas Day, nor is it a good place to insult each other. This forum is intended for describing and fixing bugs, requesting new features, and pretty much nothing else.
