### ISSUE TITLE
Dropt Incompatibility 

### ISSUE THREAD

**Issue by ghost** [PersonTheCat/ore_stone_variants#12]
The mod [Dropt](https://minecraft.curseforge.com/projects/dropt?gameCategorySlug=mc-mods&projectID=284973) is a mod that allows for you to change the drops of items depending on certain conditions and such. However sadly, there seems to be an issue with Ore Stone Variants. There is no crash or anything of that nature, but when trying to change the drops of a ore stone variant or even a specific item, nothing changes.

You could use any item or any block from any mod or even vanilla to replace the drop of an ore stone variant and the variant's ore/item will just drop. This also happens when changing ALL blocks loaded into the game to drop the same item, Ore Stone Variant still fails to drop it's designated drop.

**Comment by PersonTheCat** [comment]
Hello, sorry for the delay in getting back to you. I've just finished classes and will be looking into the mod again over the next few days. As this is one of the only bugs at the moment, it'll be one of the first things I get to. Thanks!

**Comment by PersonTheCat** [comment]
Just a quick update: I have looked into this issue, but was unable to identify a culprit. I suspect this is related to my using a function to manually spawn entities using Forge's getBlockAsItemWithChance() instead of Block#getItemDropped(). I could change this (i.e. revert back to an older version of the class), but I think it might actually be better for Dropt's devs to add support for mods that use this function. I may post this as a bug on their repository and see what they think.

**Comment by PersonTheCat** [comment]
Hello, again. Just letting you know that I have fixed this issue and can confirm that it's working for me. Please try the newest version, 2.11, once it's released and verify that it's working for you as well. 

Thanks again!
