### ISSUE TITLE
Ore Block loot tables not being modified by other mods

### ISSUE THREAD

**Issue by ildiem** [PersonTheCat/ore_stone_variants#126]
Hello! I'm running Minecraft 1.16.5 with Forge ver. 36.1.16 and Ore Stone Variants 6.1.

I'm running the mod alongside Caves & Cliffs Backport, which includes new loot tables for Iron and Gold Ore to allow them to drop Raw Iron and Raw Gold. The mod stores these loot tables under "minecraft", but OSV doesn't pull from these new loot tables when it seems to be pulling from those files by default. Does C&C Backport not modify those loot tables directly, or is there some order of operations thing which prevents OSV from accessing the modified loot tables?

I don't believe this is a bug so much as I don't have enough knowledge to understand the problem. I was hoping someone may provide some insight as to how to fix this? Thanks!

**Comment by PersonTheCat** [comment]
OSV lets you modify the loot tables in two ways:
* By pasting in a raw loot table JSON, or
* By using a resource location of an existing loot table. 

Basically, if you don't use a raw JSON, the location is passed into the regular block properties and **OSV does not determine where the loot comes from beyond that point**.

In other words, to fix this, there are two options:
* Use the raw loot table inside of the presets. OSV is designed to handle drops for you and is essentially doing the same thing as the other mod, which is why there are conflicts.
* A new feature is needed to somehow manually figure out where the top-level loot table should come from.

In my opinion, the second option is not a good choice because then I'm reimplementing behavior that is already supposed to happen in the base game. I'd prefer to never do that, if I can avoid it. 

I'll take a look after 6.2 comes out, but will most likely not change this behavior. OSV has to generate everything and is designed to handle drops, block property overrides, and custom ore generation. It's very highly specialized to avoid redundant setup between multiple ores of the same type, something that no other ore mod does. It's gonna conflict with any mod that tries to change that.

**Comment by ildiem** [comment]
Thanks for the quick reply and all the info! I think I have an idea of where to go from here, so please don't worry about looking at the second option. Thanks again!
