### ISSUE TITLE
[Request] Thaumcraft 6 Support

### ISSUE THREAD

**Issue by Voxel-Friend** [PersonTheCat/ore_stone_variants#15]
Would be nice for the overworld quartz and amber. Thank you for considering!

**Comment by Voxel-Friend** [comment]
Sweet. Also, I forgot to mention cinnabar!

**Comment by PersonTheCat** [comment]
Hello. Just letting you know that I just finished uploading a new version with support for Thaumcraft 6. Their source code isn't open, so I may have gotten a couple of values wrong, but it's all working for me. I'm going to go ahead an close this, but let me know if you encounter any issues and I'll get on it. 

Thanks!

**Comment by Voxel-Friend** [comment]
This is great! Thanks! I am a little bummed however that, without installing another mod with quartz, thaumcraft quartz isn't supported. But I suppose I like embers enough to use it.

**Comment by PersonTheCat** [comment]
Sure. Thaumcraft quartz was actually not included in the update because it already existed in OSV. There are two ways to add it: the first is using the dynamic block system, by adding "quartz_ore, stone:*" under "Variant Adder" in the config file; the new way is an option specifically created for quartz, called "Spawn Default Quartz Variants" which was created for users with mods such as Thaumcraft and Embers. You just have to change false to true because I didn't want to leave it enabled by default for users without such mods who might not want it spawning in the overworld.

Unless there's something different about Thaumcraft quartz. I'm not aware. If so, let me know and I'll work something out.
