### ISSUE TITLE
[1.16.5]Crash when the ores have been generated or placed

### ISSUE THREAD

**Issue by TUsama** [PersonTheCat/ore_stone_variants#165]
I got two crash report when the game crash. 
the world generation crash:
[crash-2022-06-20_19.32.48-server.txt](https://github.com/PersonTheCat/OreStoneVariants/files/8940268/crash-2022-06-20_19.32.48-server.txt)

crash in the superflat world when I placed a ore:
[crash-2022-06-20_19.40.11-server.txt](https://github.com/PersonTheCat/OreStoneVariants/files/8940273/crash-2022-06-20_19.40.11-server.txt)

It seems a mod incompatible problem, because I have test osv and Quark in a new instance and everything is fine. But sadly I can't allocate which mod cause this. I'll very appreciate that if you could fix this.

**Comment by PersonTheCat** [comment]
This actually sounds like a compatibility issue with Java 16. Neither MC 1.16 nor Forge 1.16 officially supports Java 16, and so it is not a compatibility target for me. 

Things you can try:
* Send me the complete log file. I setup some log statements that would confirm compatibility issues. (not seen here)
* Enable `forceCompatibilityMode` in the `osv-common` config file. This will disable dynamic block imitation and you'll lose most of the important features since OSV 6.0, but it will _work_ on newer Java versions.
* Downgrade to the officially support JVM version: 1.8. 
* Wait for OSV 1.18, which will officially support Java 16.

**Comment by TUsama** [comment]
[debug.log](https://github.com/PersonTheCat/OreStoneVariants/files/8945731/debug.log)
[latest.log](https://github.com/PersonTheCat/OreStoneVariants/files/8945732/latest.log)

Here are the latest.log and debug.log, and I agree with you that the wrong Java version causes this problem, I have tested my pack in the JVM 1.8 and no crash occurred. thanks for your help!
