### ISSUE TITLE
Suggestion: Blacklist dimensions instead of whitelist

### ISSUE THREAD

**Issue by kragnoth** [PersonTheCat/ore_stone_variants#29]
Also, would be awesome if you could control spawn rates of non-dense variants. (or am I missing something?)

**Comment by PersonTheCat** [comment]
Hello. Thanks for the suggestions! Technically, both of these things are already possible. Now, when you say blacklisting dimensions, are you referring to the global whitelist in the config file? The use of a whitelist there instead of a blacklist was actually a design choice. I chose that in preferring performance over immediate adaptability, i.e. not automatically spawning ores in all new dimensions means there's less for the CPU to worry about unless the user specifically wants that. Another user suggested ignoring the list altogether if it's empty. I forget if I ever did that. For your setup, would that make things more convenient? If not, this gives me something to think about. 

About the normal variant spawn frequency: the dense variant spawn frequency is actually a ratio, meaning that it is itself relative to each original ore's spawn frequency. If you're looking to increase the spawn frequency for certain ores, you can easily create a new WorldGenProperties.json with only the vein size and / or frequency inside to get higher counts. I actually do something similar with my own setup. I prefer fewer, but much larger coal veins. If you mean a global setting to increase ore counts, I might do something similar to that. I like the idea, but I may mix it up just slightly. 

I love getting this kind of feedback. Hit me with any more ideas you have and I'll see what I can do.

**Comment by kragnoth** [comment]
Oh, the blacklist was simply to account for randomly generated dimension ID's like mystcraft uses.  No real way for pack devs to know all the dimensions with mystcraft/rftools dimensions.  And thanks for the other suggestion, I'll look into the json override that you mentioned.

**Comment by PersonTheCat** [comment]
Just letting you know that I made the change I was mentioning before. Leaving the list empty will now allow ores to generate in any dimension. I could still add the option to globally override the frequency of ore spawns, but I hesitate in case that would cause issues. Let me work on it a bit. In the meantime, I may go ahead and close this issue. Please let me know of any other suggestions or issues you have and I'll get to them as soon as possible.
