### ISSUE TITLE
1.12.2 not on the github?

### ISSUE THREAD

**Issue by Iamgoofball** [PersonTheCat/ore_stone_variants#34]
I was planning to look into figuring out automating the finding and dense-ifying of ores, but I couldn't find the 1.12.2 source for the mod. Is it located at another repository or is it just not uploaded yet? Also, is there a better way to get ahold of you aside from github comments?

**Comment by PersonTheCat** [comment]
Hello. I'm not really sure what you mean by automating this process. If you can help me understand what you're looking for, I might be able to help you figure that out. Second, the code in this repository actually is for 1.12.2. The game is similar enough between those versions that I'm usually able to get everything working in both of them at once. And about contacting me, this is actually a really good forum for that. I get notified right away and can usually respond fairly quickly. For most issues and questions, at least.

**Comment by Iamgoofball** [comment]
Right, what I wanted to look into was if it was possible to abuse the ore dictionary to, instead of manually having to add a mod's ores to the config or to the mod's built-in compatibility setups, just scan the ore lists and generate (dense) stone variants for any ores it finds.

**Comment by Iamgoofball** [comment]
Upon checking things out, are you absolutely certain the codebase is for 1.12.2? As when loaded into an mcp/forge setup for 1.12.2, there's a variety of errors.

**Comment by PersonTheCat** [comment]
It is. I use this in 1.12.2 all the time, but it is out of date by a version or two. I'll upload that in the next hour or so. If that doesn't work, you may just need to stick with 1.12.1. It will still compile and run in 1.12.2. Also, just to confirm, you mean adding stone variants and not new ore types, right? Adding new ore types automatically has been requested before, but there's no way to access some information without doing it reflectively, which would be fairly complicated and most likely unreliable, in this case. Especially when it comes to information about how those ores are supposed to generate in the world, because there's no standard method that everyone uses  There is a tool in the config file which will attempt to find or approximate as much information as it can, but it's really only about 65-70% reliable. Using that, at least, is probably not a great idea.

**Comment by PersonTheCat** [comment]
Hey, I just wanted you to know that I made some more progress with handling dynamically-registered ore properties. I still don't think there's any good way to automatically handle adding new ores based on what's registered by other mods, at least while correctly handling the world generation variables, but I think this could be a good compromise. Regardless, I'm going to close this now because it's a bit out of date with how things have changed. Please let me know if you have any other ideas. I'd love to continue discussing what can be done with this mod. Thanks again!
