### ISSUE TITLE
Embers Rekindled Crash on start up with version 4.2 of OSV

### ISSUE THREAD

**Issue by yikies** [PersonTheCat/ore_stone_variants#52]
looks like it cant find the lead ore texture

https://paste.dimdev.org/gonucejuyi.mccrash

**Comment by kragnoth** [comment]
Did you do a fresh config? I remember one of the kindles ores being written incorrectly in one of the versions.

**Comment by yikies** [comment]
yeah i remember that, that was a typo with silver ore. this is different i dont know how to fix this

**Comment by PersonTheCat** [comment]
Hi, there. At first, I suspected this was related to using Embers Rekindled, instead of just normal Embers. However, I actually tried using the same version of EK and was not able to reproduce the issue, even with a clean resources.zip. Have you tried using just these two mods together? If not, is there any way you could try that and get back to me? It would help to know whether this is related to some other mod or even OS, MC settings, OSV or EK settings, or anything else.

**Comment by yikies** [comment]
hm okay, i just tried it out with just EK, Soot, OSV, and Immersive Engineering with the same config I used with my modpack and I didn't get the crash. Now I have no idea what could be causing it.

**Comment by yikies** [comment]
okay.... so manually setting all ore veins to 0 in the embers config fixed it?? i think. it just started working randomly
