### ISSUE TITLE
Some more suggestions for integration

### ISSUE THREAD

**Issue by CactusDuud** [PersonTheCat/ore_stone_variants#54]
- [Utility Base Ores](https://minecraft.curseforge.com/projects/utility-base-ores)
- [TAIGA](https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon)
- [Astral Sorcery](https://minecraft.curseforge.com/projects/astral-sorcery)
- [Traverse stone types](https://minecraft.curseforge.com/projects/traverse)
- Biomes o' Plenty's hardened ice as a "stone" type
- [NetherEx netherrack variants](https://minecraft.curseforge.com/projects/netherex)
- native support for nether/end generation?

I'm not sure if this is already possible, but can you configure this mod to create gravel ores like in old tinker's construct? Relatedly, is it possible to make ores require the harvesting tool of the ore but the hardness/harvesting time of the regular block (for example, gold ores in wood blocks require an iron axe)?

**Comment by PersonTheCat** [comment]
Oh, boy. I somehow missed this message at first, but I'm not sure how. Thanks for the ideas! I've got just a few more days of class this semester (and until I graduate) and I can't wait to get back into this project. For now, I'll say a few things: 
- I may not do BOP's hardened ice because I don't think it's necessarily thematically appropriate. However, you can definitely add support for this manually in the config file. It should be fairly easy and you're welcome to let me know if you need help setting it up.
- You definitely can create gravel ores. Check the ore registry in the config file.
- Ores with custom background properties will blend properties between ore and background block. So, ores inside of wood require an axe by default, although this can be configured in the config file.
Let me know if you have any other ideas and I'll get back to you as soon as possible.

**Comment by KingCactaur** [comment]
Thanks for the kind response! How might you go about adding gravel ores? I attempted to mess with the config myself and ended up just getting a bunch of errors.

**Comment by PersonTheCat** [comment]
Hey, there. Sorry again. :3 There are a couple of ways you can handle this easily. The first thing is to take the ore group you're looking to add support for (or just use `all`) and just type `<group_name> gravel` under "Add Blocks Here." e.g. type `all gravel`, and that's it. Another way to do it is to make gravel be a part of a standard block group. So, for example, you could edit the `minecraft` BlockGroup by adding a line that reads `gravel` and then that will become the fifth state of all standard variants. If you do try something and it isn't working, feel free to let me know or send me your config and I'll test it out for you. 
I should also be a little bit more available now, now that finals are over and I've graduated. Hope this helps!

**Comment by PersonTheCat** [comment]
Hey, thanks for helping me clean this up! I appreciate it.
