### ISSUE TITLE
Crash with HammerX mod

### ISSUE THREAD

**Issue by Bulldog83** [PersonTheCat/ore_stone_variants#59]
I've taken the crash when I've try to broke some of your ore with hammer from HammerX.

There are 4 crash logs.

https://gist.github.com/Bulldog83/7264833f819d58da11e8dea877462227

Minecraft: 1.12.2
Forge: 14.23.5.2768
OSV: 4.3
HammerX: 1.1.4

**Comment by PersonTheCat** [comment]
Hey, there. Thanks for reporting this! I'm honestly not sure why this might occur, but I suspect it's more on the side of HammerX than OSV. I'll be taking a deeper look at this at some point to see what I can do to mitigate it. In the meantime, you may be able to avoid the crash by disabling background block imitation in the config file. This will make variants function just like normal ores, avoiding the code that crashes.

**Comment by PersonTheCat** [comment]
Correct, but it appears that this happens when non-OSV blocks are polled as though they were OSV blocks. According to the crash, it's trying to get properties from `minecraft:stone` and `minecraft:air` by calling `BlockOresBase#getMaterial`, which of course yields various crashes. I believe there isn't really all that much I can do to work around this. :/
