### ISSUE TITLE
Tryna make the ores spawn a bit differently in different dimensions.

### ISSUE THREAD

**Issue by Goy288** [PersonTheCat/ore_stone_variants#80]
Specifically for things like The End and the Nether with their fundamentally different layouts, is it possible to make the ore spawning differ between dimensions?

**Comment by PersonTheCat** [comment]
It is, actually. It's a bit tedious because you need to create presets for every single ore that you want to customize, but it's hopefully not too bad. You just create a folder or zip file for each ore properties you want to change and then place a WorldGenProperties.json inside of each one based on (this template)[https://pastebin.com/jf9zTuiN]. Hope this helps! Let me know if you need help in the process and feel free to join the Discord server if you need something a little quicker.

**Comment by Goy288** [comment]
Alright, thanks for the help! I'll let you know how it turns out.

**Comment by Goy288** [comment]
Yeah, I couldn't really figure out how to change the WorldGenProperties.json successfully, so I decided to outright just give up on changing the world gen for The End, and now I'm just change the world gen config in the NetherEX mod to spawn the ores in their respective Nether biomes. 

It wouldn't really make much sense to mine in The End anyway with the constant danger of falling into the void. I'm not closing this thread though, just in case if you or someone else figures it out.

**Comment by PersonTheCat** [comment]
I've tested this again just to be safe and was definitely able to get it working. Not sure what was going on. If you like, you can send me your presets directly and I'll try them out for you.

**Comment by Goy288** [comment]
Sorry for not responding earlier, I was working on stuff at the time.

Anyway, here are my old presets. I already zipped them up a while ago, in case if I ever wanted to go back to them.
[unsucessful_dim_changes.zip](https://github.com/PersonTheCat/ore_stone_variants/files/3807172/unsucessful_dim_changes.zip)

**Comment by PersonTheCat** [comment]
I hate to close this without ever verifying that the issue was fixed, but the preset system has completely changed at this point and so it no longer really applies.
